// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTd7W7LtGpuYstuSNCSbmW_A8TXWK21k',
    appId: '1:668703648575:android:2346eddd202e6bfc03418a',
    messagingSenderId: '668703648575',
    projectId: 'trupressed-7fb72',
    databaseURL:
        'https://trupressed-7fb72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trupressed-7fb72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqYqDX8f3V6BlVt8aPYEnwd6RvI7Rpt6k',
    appId: '1:668703648575:ios:c8269aca7ce22a1803418a',
    messagingSenderId: '668703648575',
    projectId: 'trupressed-7fb72',
    databaseURL:
        'https://trupressed-7fb72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trupressed-7fb72.appspot.com',
    iosBundleId: 'co.proglabs.foodizmSubscription',
  );

}
